28/mjhea0/project/server/models.py
# project/server/models.py


import datetime

from project.server import app, db


class Rate(db.Model):

    __tablename__ = "rates"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    currency = db.Column(db.String(255), nullable=False)
    price = db.Column(db.DECIMAL(), nullable=False)
    timestamp = db.Column(db.DateTime, nullable=False)

    def __init__(self, currency, price, timestamp=datetime.datetime.utcnow()):
        self.currency = currency
        self.price = price
        self.registered_on = timestamp

    def __repr__(self):
        return '<Rate {0}>'.format(self.currency)

28/mjhea0/project/__init__.py
# project/__init__.py

28/mjhea0/project/server/__init__.py
# project/server/__init__.py


import os

from flask import Flask, render_template
from flask_debugtoolbar import DebugToolbarExtension
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy


app = Flask(
    __name__,
    template_folder='../client/templates',
    static_folder='../client/static'
)


app_settings = os.getenv(
    'APP_SETTINGS', 'project.server.config.DevelopmentConfig')
app.config.from_object(app_settings)

toolbar = DebugToolbarExtension(app)
bootstrap = Bootstrap(app)
db = SQLAlchemy(app)

from project.server.main.views import main_blueprint
app.register_blueprint(main_blueprint)


@app.errorhandler(401)
def unauthorized_page(error):
    return render_template("errors/401.html"), 401


@app.errorhandler(403)
def forbidden_page(error):
    return render_template("errors/403.html"), 403


@app.errorhandler(404)
def page_not_found(error):
    return render_template("errors/404.html"), 404


@app.errorhandler(500)
def server_error_page(error):
    return render_template("errors/500.html"), 500

28/mjhea0/project/server/main/__init__.py
# project/server/main/__init__.py

28/mjhea0/project/server/main/views.py
# project/server/main/views.py


import datetime
from bokeh.plotting import figure
from bokeh.embed import components
from bokeh.resources import INLINE
from flask import render_template, Blueprint
from flask_sqlalchemy import SQLAlchemy

from project.server.models import Rate


main_blueprint = Blueprint('main', __name__,)


@main_blueprint.route('/')
def home():
    historical = get_historical_data()
    chart = create_chart(historical)

    # grab the static resources
    js_resources = INLINE.render_js()
    css_resources = INLINE.render_css()

    # render template
    script, div = components(chart)

    return render_template(
        'main/home.html',
        points=len(historical),
        plot_script=script,
        plot_div=div,
        js_resources=js_resources,
        css_resources=css_resources,
    )


def get_historical_data():
    results = Rate.query.all()
    return [u.__dict__ for u in results]


def create_chart(data):
    data.sort(key=lambda d: d['timestamp'])
    # create figure
    p = figure(
        x_axis_label='time',
        y_axis_label='price',
        x_axis_type="datetime",
        width=1000,
        height=500
    )
    # get x and y axis data
    curr_1_x = []
    curr_1_y = []
    curr_2_x = []
    curr_2_y = []
    curr_3_x = []
    curr_3_y = []

    for value in data:
        time = datetime.datetime.strptime(
            str(value['timestamp']), '%Y-%m-%d %H:%M:%S')
        if value['currency'] == 'bitstamp':
            curr_1_x.append(time)
            curr_1_y.append(value['price'])
        if value['currency'] == 'kraken':
            curr_2_x.append(time)
            curr_2_y.append(value['price'])
        if value['currency'] == 'bittrex':
            curr_3_x.append(time)
            curr_3_y.append(value['price'])

    p.line(curr_1_x, curr_1_y, color='red', legend='bitstamp', line_width=2)
    p.line(curr_2_x, curr_2_y, color='green', legend='kraken', line_width=2)
    p.line(curr_3_x, curr_3_y, color='black', legend='bittrex', line_width=2)
    p.legend.location = 'bottom_left'

    return p

28/mjhea0/project/client/templates/_base.html
<!DOCTYPE html>
<html>

  <head>
    <meta charset="utf-8">
    <title>Flask + Bokeh{% block title %}{% endblock %}</title>
    <!-- meta -->
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- styles -->
    <link href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.1/yeti/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="{{url_for('static', filename='main.css')}}" rel="stylesheet" media="screen">
    {% block css %}{% endblock %}
  </head>

  <body>

    {% include 'header.html' %}

    <div class="site-content">
      <div class="container">

        <!-- messages -->
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <br>
        <div class="row">
          <div class="col-md-12">
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
              <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
             {{message}}
            </div>
            {% endfor %}
          </div>
        </div>
        {% endif %}
        {% endwith %}


        <!-- child template -->
        {% block content %}{% endblock %}

        <br>

        <!-- errors -->
        {% if error %}
          <p class="error"><strong>Error:</strong> {{ error }}</p>
        {% endif %}

      </div>
    </div>

    <br><br>

    {% include 'footer.html' %}

    <!-- scripts -->
    <script src="//code.jquery.com/jquery-1.11.2.min.js" type="text/javascript"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="{{url_for('static', filename='main.js')}}" type="text/javascript"></script>
    {% block js %}{% endblock %}

  </body>
</html>

28/mjhea0/project/client/templates/footer.html
<footer>
  <div class="container">
    <small>
      <span>© <a href="mailto:michael@realpython.com">Real Python</a></span>
    </small>
  </div>
</footer>

28/mjhea0/project/client/templates/header.html
<header class="site-header">
  <!-- Navigation -->
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
          <a class="navbar-brand" href="{{ url_for('main.home') }}">Flask + Bokeh</a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
        </ul>
        <ul class="nav navbar-nav navbar-right">
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
  </nav>
</header>

28/mjhea0/project/client/templates/main/home.html
{% extends "_base.html" %}

{% block content %}

{{ js_resources|indent(4)|safe }}
{{ css_resources|indent(4)|safe }}
{{ plot_script|indent(4)|safe }}

<div class="body-content">
  <div class="row">
    <h1>Historical Rates</h1>
    <hr><br>
    {{ plot_div|indent(4)|safe }}
    <br>
    <p>Total Data Points - {{ points }}</p>
  </div>
</div>

{% endblock %}